name: Build and Release Tauri App

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install dependencies
        run: |
          npm install
          
      - name: Generate release date
        id: date
        run: |
          echo "RELEASE_DATE=$(date +'Release %m-%d-%y-%H%M%S')" >> $GITHUB_ENV
          echo "TAG_DATE=$(date +'%m-%d-%y-%H%M%S')" >> $GITHUB_ENV
          
      - name: Build Tauri app
        run: npm run tauri build
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_DATE }}
          name: ${{ env.RELEASE_DATE }}
          draft: false
          prerelease: false
          files: |
            src-tauri/target/release/bundle/macos/*.app
